version: '3'
services:
  app:
    container_name: backend1234
    build: ./
    env_file:
      - ./env_ports.env
    links:
      - mongo
    ports:
      - 5002:5000  
    depends_on:
      - mongo
  
  
  mongo:
    container_name: dbase
    image: mongo
